"""updating product table

Revision ID: 281a36c2e8ca
Revises: cfe3f3f69efd
Create Date: 2024-09-18 14:30:33.820268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '281a36c2e8ca'
down_revision = 'cfe3f3f69efd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
