"""Adding constraints

Revision ID: 570cf8f8b9f5
Revises: 98dfc5db67bd
Create Date: 2024-09-23 02:16:06.400977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '570cf8f8b9f5'
down_revision = '98dfc5db67bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customers', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('customers', 'phone',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('customers', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('customers', 'address',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.create_unique_constraint(None, 'customers', ['email'])
    op.alter_column('products', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('products', 'price',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               nullable=False)
    op.alter_column('products', 'category',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('products', 'supplier_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('sales', 'customer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('sales', 'sale_date',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('sales', 'total_amount',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.alter_column('sales_details', 'sale_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('sales_details', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('sales_details', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('sales_details', 'price',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.create_foreign_key(None, 'sales_details', 'products', ['product_id'], ['id'])
    op.alter_column('suppliers', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('suppliers', 'phone_number',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('suppliers', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('suppliers', 'address',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.create_unique_constraint(None, 'suppliers', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'suppliers', type_='unique')
    op.alter_column('suppliers', 'address',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('suppliers', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('suppliers', 'phone_number',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('suppliers', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_constraint(None, 'sales_details', type_='foreignkey')
    op.alter_column('sales_details', 'price',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.alter_column('sales_details', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('sales_details', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('sales_details', 'sale_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('sales', 'total_amount',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.alter_column('sales', 'sale_date',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('sales', 'customer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('products', 'supplier_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('products', 'category',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('products', 'price',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               nullable=True)
    op.alter_column('products', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'customers', type_='unique')
    op.alter_column('customers', 'address',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('customers', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('customers', 'phone',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('customers', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
