"""updating  tables

Revision ID: 6ce8be1bbdc1
Revises: 281a36c2e8ca
Create Date: 2024-09-18 21:00:05.778099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ce8be1bbdc1'
down_revision = '281a36c2e8ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
