"""updating main

Revision ID: 98dfc5db67bd
Revises: 6ce8be1bbdc1
Create Date: 2024-09-18 22:53:31.749504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98dfc5db67bd'
down_revision = '6ce8be1bbdc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
