"""updating tables

Revision ID: bc7383f108d4
Revises: 98dfc5db67bd
Create Date: 2024-09-23 13:44:03.929392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc7383f108d4'
down_revision = '98dfc5db67bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
